/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_example_ukasz_findface_OpenCvCamera.h"

JNIEXPORT void JNICALL Java_com_example_ukasz_findface_OpenCvCamera_faceDetector
  (JNIEnv *, jclass, jlong camRgba) {
//    Mat& image = *(Mat*)camRgba;
//
//
//    detectFace(image);
}

//void detectFace(Mat& image) {
//
//}

