/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ukasz_findface_OpenCvCamera */

#ifndef _Included_com_example_ukasz_findface_OpenCvCamera
#define _Included_com_example_ukasz_findface_OpenCvCamera
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
