/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_example_ukasz_findface_OpenCvCamera.h"

JNIEXPORT void JNICALL Java_com_example_ukasz_findface_OpenCvCamera_faceDetector
  (JNIEnv *, jclass, jlong camRgba) {
    Mat& image = *(Mat*)camRgba;


   detectFace(image);
}

JNIEXPORT void JNICALL Java_com_example_ukasz_findface_OpenCvCamera_blackWhiteMode
(JNIEnv *, jclass, jlong camRgba) {
    Mat& image = *(Mat*)camRgba;


    blackWhiteMode(image);
}

JNIEXPORT void JNICALL Java_com_example_ukasz_findface_OpenCvCamera_moveDetector
(JNIEnv *, jclass, jlong camRgba) {
    Mat& image = *(Mat*)camRgba;

    detectMove(image);
}

JNIEXPORT void JNICALL Java_com_example_ukasz_findface_OpenCvCamera_moveDetectorBetter
(JNIEnv *, jclass, jlong camRgba, jboolean changedMode) {
Mat& image = *(Mat*)camRgba;


detectMoveBetter(image, changedMode);
}

JNIEXPORT void JNICALL Java_com_example_ukasz_findface_OpenCvCamera_lightDetector
(JNIEnv *, jclass, jlong camRgba) {
    Mat& image = *(Mat*)camRgba;


    detectLight(image);
}

void blackWhiteMode(Mat& image) {
    cvtColor(image, image, COLOR_BGR2GRAY);
}

void detectFace(Mat& frame) {

}

Mat lastImage; // poprzednia klatka
bool first = true;
void detectMove(Mat& image) {
    cvtColor(image, image, COLOR_BGR2GRAY);
    if(first) {
        first = false;
        lastImage = image.clone();
    } else {
        absdiff(image, lastImage, image);
        lastImage = image.clone();
    }

}

bool frst = true;
Mat firstImage; // pierrwsza klatka
void detectMoveBetter(Mat& image, bool mode) {
    cvtColor(image, image, COLOR_BGR2GRAY);
    if(mode) {
        frst = true;
    }
    if(frst) {
        frst = false;
        firstImage = image.clone();
    } else {
        absdiff(image, firstImage, image);
    }
}

void detectLight(Mat& image) {
    Mat img = image.clone();
   // cvtColor(image, hsv, CV_BGR2HSV);

    int cols = img.size().width;
    int rows = img.size().height;

    for(int i=0; i<rows; i++) {
        for(int l=0; l<cols; l++) {
            Vec3f color = img.at<Vec3b>(i,l);
          //  image.data[image.channels()*(image.rows*i + l)];

            if(color[0] > 230 && color[1] > 235 && color[2] > 218) {
              //  img.at<uchar>(i, l) = 128;
               // image.at<Vec3b>(i,l)[0] = 0;
                color[0] = 0;
                color[1] = 0;
                color[2] = 255;
                img.at<Vec3b>(i,l) = color;

            }

        }
    }

    image = img.clone();


}

